# Form implementation generated from reading ui file 'C:\Users\user\PycharmProjects\PythonProject1\Second Task\UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(parent=MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(150, 250, 100, 30))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random Circles"))
        self.pushButton.setText(_translate("MainWindow", "Generate Circles"))
